### ISSUE TITLE
Error: Cannot find module 'ajv/dist/core'

### ISSUE THREAD

**Issue by stefanofalasca** [OfficeDev/generator-office#739]
# Prerequisites

- [X] I am running the latest version of Node and the tools
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

# Expected behavior
When I run npm start work

# Current behavior
I am started to create a new office addin angular task pane project. When I run npm start, I am getting follow error:
![image](https://user-images.githubusercontent.com/1249181/199042103-1e3a098a-b462-4966-9504-4e6e89f2eb54.png)

**Comment by millerds** [comment]
Is this behavior reproducible with a new project?  Have you tried running 'npm install' in the project to correct it?

Yeoman generator runs 'npm install' at the end of the project generation, but for some reason occasionally the command fails for some reason (not specific to office add-in projects).  In those cases, running it manually should fix it.

**Comment by stefanofalasca** [comment]
Yes, I created a new project like from documentation, I deleted node_modules folder, I ran npm install and then npm start. Very easy

**Comment by millerds** [comment]
Did that correct the problem or was is still there?

**Comment by stefanofalasca** [comment]
Problem still there.

**Comment by stefanofalasca** [comment]
Any Solutions ? See angular projects doesn't work

**Comment by millerds** [comment]
I just noticed that you are using node v18.  I realize that has become the new LTS branch of node, but we have not been able to check our tooling and projects against that version yet.  Do you have the same problem when using node v16 (and the corresponding version of npm)?

**Comment by millerds** [comment]
I just tried this with node 18 and it worked fine for me.  What documentation are you following to create the project?

**Comment by stefanofalasca** [comment]
I solved using "office-addin-debugging": "^4.3.14",

**Comment by DonkeyKongJr** [comment]
Got the very same issue today. It neither works with Node.js v18.17.0 nor with office-addin-debugging": "^4.3.14"?!

`> npm start   

> office-addin-taskpane-js@0.0.1 start
> office-addin-debugging start manifest.xml

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'ajv/dist/core'
Require stack:`

**Comment by paule96** [comment]
We found the same problem. But we needed to do both fixes. So we changed `office-addin-debugging` to `^4.3.14` and we did run `npm install --save-dev ajv`

thanks to (@DanielHabenicht)

**Comment by Davidihl** [comment]
Working with `node 20.10.0` using `npm install --save-dev ajv` solved the issue for me too

**Comment by sandyeveliz** [comment]
> Working with `node 20.10.0` using `npm install --save-dev ajv` solved the issue for me too

This fix my issue for node 20 too, thanks @Davidihl

**Comment by Bilawal-muzaffar** [comment]
**npm install --save-dev** ajv solved the problem

**Comment by Makkalay** [comment]
https://github.com/ajv-validator/ajv/issues/2452

**Comment by berdev80381** [comment]
npm install ajv@latest ajv-keywords@latest
solved it for me

**Comment by poperechnyi1** [comment]
I have run
`npm install --save-dev ajv`

Also added into **compilerOptions**
```
 "typeRoots": [
      "./node_modules/@types",
    ],
    "types": [
      "node"
    ],
```

**Comment by vidurpunj** [comment]
node -v = v14.21.3
Below command fixed the issue:
npm install --save-dev ajv
